// resources/js/Pages/Auth/Login.vue
<template>
  <div class="Box"></div>
  <div class="p-6 bg-indigo-800 min-h-screen flex justify-center items-center">
    <div class="w-full max-w-md">
      <form class="mt-8 bg-white rounded-lg shadow-xl overflow-hidden" @submit.prevent="login">
        <div class="px-10 py-12">
          <h1 class="text-center font-bold text-3xl">Welcome Back!</h1>
          <div class="mx-auto mt-6 w-24 border-b-2" />
          <input type="email" v-model="form.email" class="mt-10" autofocus autocapitalize="off" >
          <input type="password" v-model="form.password" class="mt-6"  >
          <label class="mt-6 select-none flex items-center" for="remember">
            <input id="remember" v-model="form.remember" class="mr-1" type="checkbox" />
            <span class="text-sm">Remember Me</span>
          </label>
        </div>
        <div class="px-10 py-4 bg-gray-100 border-t border-gray-100 flex">
          <button class="ml-auto btn-success" type="submit">Login</button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      form: this.$inertia.form({
        email: 'johndoe@example.com',
        password: 'secret',
        remember: false,
      }),
    }
  },
  methods: {
    login() {
      this.form.post(this.route('login'))
    },
  },
  mounted() {
    console.log('component mounted')
  }
}
</script>

// resources/js/Pages/Auth/Login.jsx
import React, { useEffect } from 'react';
import Checkbox from '@/Components/Checkbox';
import Input from '@/Components/Input';
import Label from '@/Components/Label';
import ValidationErrors from '@/Components/ValidationErrors';
import { Head, Link, useForm } from '@inertiajs/inertia-react';
import {Box, Button, FormControl, Header, TextInput} from "@primer/react";

const Login = ({ status, canResetPassword }) => {
    const { data, setData, post, processing, errors, reset } = useForm({
        email: '',
        password: '',
        remember: '',
    });

    useEffect(() => {
        return () => {
            reset('password');
        };
    }, []);

    const onHandleChange = (event) => {
        setData(event.target.name, event.target.type === 'checkbox' ? event.target.checked : event.target.value);
    };

    const submit = (e) => {
        e.preventDefault();

        post(route('login'));
    };

    return (
        <Box display="flex">
            {status && <div className="mb-4 font-medium text-sm text-green-600">{status}</div>}

            <ValidationErrors errors={errors} />

            <form onSubmit={submit} className="col-md-4 mx-auto mt-10">
                <FormControl>
                    <FormControl.Label forInput="email">
                        Email
                    </FormControl.Label>

                    <TextInput
                        type="text"
                        name="email"
                        value={data.email}
                        block
                        autoComplete="username"
                        isFocused={true}
                        handleChange={onHandleChange}
                    />
                </FormControl>

                <FormControl>
                    <FormControl.Label forInput="password">
                        Password
                    </FormControl.Label>

                    <TextInput
                        type="password"
                        name="password"
                        value={data.password}
                        block
                        autoComplete="current-password"
                        handleChange={onHandleChange}
                    />
                </FormControl>

                <div className="block mt-4">
                    <label className="flex items-center">
                        <Checkbox name="remember" value={data.remember} handleChange={onHandleChange} />

                        <span className="ml-2 text-sm text-gray-600">Remember me</span>
                    </label>
                </div>

                <div className="flex items-center justify-end mt-4">
                    {canResetPassword && (
                        <Link
                            href={route('password.request')}
                            className="underline text-sm text-gray-600 hover:text-gray-900"
                        >
                            Forgot your password?
                        </Link>
                    )}

                    <Button className="ml-4" processing={processing}>
                        Log in
                    </Button>
                </div>
            </form>
        </Box>
    );
}

export default Login
